import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const dictionary = {
  en: {
    "login_title": "Login to Nordle",
    "username_placeholder": "Enter Username...",
    "login_btn": "Start Decrypting",
    "subtitle": "CRACK THE CODE",
    "play_offline": "Play Offline",
    "play_online": "Play Online",
    "metrics": "Metrics",
    "settings": "Settings",
    "choose_diff": "Choose Difficulty",
    "digits": "digits",
    "tries": "tries",
    "score_mult": "x score multiplier",
    "solo": "Solo",
    "pvp": "PvP",
    "metrics_title": "Metrics & Stats",
    "match_history": "Match History",
    "global_leaderbd": "Global Leaderboard",
    "rank": "Rank",
    "username": "Username",
    "wins": "Wins",
    "losses": "Losses",
    "select_lang": "Language / اللغة",
    "settings_title": "Settings",
    "games_played": "Games Played",
    "win_rate": "Win Rate",
    "total_score": "Total Score",
    "won": "Won",
    "lost": "Lost",
    "draw": "Draw",
    "round": "Round",
    "waiting_opp": "Waiting for Opponent...",
    "game_over": "Game Over",
    "victory": "You Cracked It!",
    "defeat": "You Failed!",
    "secret_was": "The secret was: ",
    "home_btn": "Home",
    "play_again_btn": "Play Again",
    "global_stats": "Global Stats",
    "played": "Played",
    "avg_tries": "Avg Tries",
    "online_record": "Online Record",
    "matches": "Matches",
    "rounds_won": "Rounds Won",
    "login_subtitle": "Enter a username to continue",
    "matchmaking": "MATCHMAKING",
    "queuing_for": "Queuing for ",
    "mode": " Mode...",
    "cancel": "Cancel",
    "quit": "Quit",
    "round_of": "Round",
    "vs": "vs",
    "out_of_tries": "Out of Tries!",
    "waiting_opp_finish": "Waiting for opponent to finish...",
    "you_won_round": "You won the round!",
    "round_draw": "Round Draw",
    "opp_won_round": "Opponent won the round!",
    "next_round": "Next round starting soon...",
    "match_victory": "MATCH VICTORY!",
    "match_draw": "MATCH DRAW!",
    "match_defeat": "MATCH DEFEAT!",
    "score": "Score: ",
    "return_menu": "Return to Menu",
    "credits_btn": "About the Developer",
    "credits_text": "This app is entirely developed and programmed by Mostafa Mohamed. Future games coming soon!",
    "htp_title": "How To Play",
    "htp_step1": "Guess the secret numeric code in the given number of tries.",
    "htp_step2": "Each guess must be a valid sequence of digits.",
    "htp_step3": "After each guess, the color of the tiles will change to show how close your guess was.",
    "htp_green": "Green: The digit is in the code and in the correct spot.",
    "htp_yellow": "Yellow: The digit is in the code but in the wrong spot.",
    "htp_gray": "Gray: The digit is not in the code at all."
  },
  ar: {
    "login_title": "تسجيل الدخول",
    "username_placeholder": "أدخل اسم المستخدم...",
    "login_btn": "ابدأ فك الشفرة",
    "subtitle": "حل الشفرة",
    "play_offline": "طاولة لعب فردي",
    "play_online": "اللعب مع آخرين",
    "metrics": "الإحصائيات",
    "settings": "الإعدادات",
    "choose_diff": "اختر الصعوبة",
    "digits": "أرقام",
    "tries": "محاولات",
    "score_mult": "مضاعف النقاط x",
    "solo": "فردي",
    "pvp": "ضد لاعب",
    "metrics_title": "الإحصائيات والأرقام",
    "match_history": "تاريخ المباريات",
    "global_leaderbd": "لائحة المتصدرين",
    "rank": "المرتبة",
    "username": "اللاعب",
    "wins": "انتصارات",
    "losses": "خسائر",
    "select_lang": "Language / اللغة",
    "settings_title": "الإعدادات",
    "games_played": "المباريات الملعوبة",
    "win_rate": "معدل الفوز",
    "total_score": "مجموع النقاط",
    "won": "فوز",
    "lost": "خسارة",
    "draw": "تعادل",
    "round": "جولة",
    "waiting_opp": "في انتظار المنافس...",
    "game_over": "انتهت اللعبة",
    "victory": "لقد حللت الشفرة!",
    "defeat": "لقد فشلت!",
    "secret_was": "الرقم السري كان: ",
    "home_btn": "الرئيسية",
    "play_again_btn": "العب مرة أخرى",
    "global_stats": "الإحصائيات العالمية",
    "played": "لعب",
    "avg_tries": "متوسط المحاولات",
    "online_record": "السجل على الإنترنت",
    "matches": "مباريات",
    "rounds_won": "جولات الفوز",
    "login_subtitle": "أدخل اسم المستخدم للمتابعة",
    "matchmaking": "البحث عن مباراة",
    "queuing_for": "في الانتظار للعب بنمط ",
    "mode": "...",
    "cancel": "إلغاء",
    "quit": "خروج",
    "round_of": "جولة",
    "vs": "ضد",
    "out_of_tries": "نفدت المحاولات!",
    "waiting_opp_finish": "في انتظار انتهاء الخصم...",
    "you_won_round": "لقد فزت بالجولة!",
    "round_draw": "تعادل في الجولة",
    "opp_won_round": "فاز الخصم بالجولة!",
    "next_round": "الجولة التالية ستبدأ قريباً...",
    "match_victory": "انتصار في المباراة!",
    "match_draw": "تعادل في المباراة!",
    "match_defeat": "هزيمة في المباراة!",
    "score": "النتيجة: ",
    "return_menu": "العودة للقائمة",
    "credits_btn": "عن المطور",
    "credits_text": "هذا التطبيق تم تطويره وبرمجته بالكامل بواسطة مصطفى محمد، ألعاب مستقبلية قادمة قريباً!",
    "htp_title": "طريقة اللعب",
    "htp_step1": "خمن الرمز الرقمي السري في عدد محدد من المحاولات.",
    "htp_step2": "كل تخمين يجب أن يكون تسلسلاً صحيحاً من الأرقام.",
    "htp_step3": "بعد كل تخمين، سيتغير لون المربعات لتوضيح مدى صحة تخمينك.",
    "htp_green": "الأخضر: الرقم الصحيح وفي المكان الصحيح.",
    "htp_yellow": "الأصفر: الرقم الصحيح ولكن في المكان الخاطئ.",
    "htp_gray": "الرمادي: الرقم غير موجود في الرمز على الإطلاق."
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('nordle_lang') || 'en');

  useEffect(() => {
    localStorage.setItem('nordle_lang', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }, [lang]);

  const t = (key) => dictionary[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
